import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"
import "./globals.css";

export const metadata = {
    title : 'Flexibble' ,
    description : "Generated By Janesh Timilsena",
}

export default function RootLayout({
    children,
}:{
    childrn : React.ReactNode
}) {
    return (
        <html lang="en">
            <body>

                <Navbar/>

                <main>
                {children}
                </main>

                <Footer/>

            </body>
        </html>
    )
}